repository:
    # See https://developer.github.com/v3/repos/#edit for all available settings.

    description: Page HTML
    homepage: http://edu.iepscf-uccle.be/moodle/course/view.php?id=437
    has_downloads: true
    has_issues: false
    has_projects: false
    has_wiki: false

    default_branch: master
